### ISSUE TITLE
Comments needed for tutorials

### ISSUE THREAD

**Issue by ashwin4ever** [omarsar/nlp_with_tensorflow#1]
Hi, these tutorials seem to be very good, but as a beginner researcher learning deep learning models, these tutorials would be even more helpful if there were comments (alongside the code) explaining the concepts in jupyter notebooks

**Comment by omarsar** [comment]
I understand. As mentioned in the README, I will be working on improving these tutorials in the next couple of days. I will get back once I can properly add comments to these tutorials. Thanks for your interest and your comments.

**Comment by ashwin4ever** [comment]
Thank you and hope the tutorial series continues... wishing the very best
